import { CheckCircle, Copy, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useToast } from "@/hooks/use-toast";
import ReactMarkdown from "react-markdown";

interface SolutionDisplayProps {
  solution: string;
  capturedImage?: string;
}

export const SolutionDisplay = ({ solution, capturedImage }: SolutionDisplayProps) => {
  const { toast } = useToast();

  const copyToClipboard = () => {
    navigator.clipboard.writeText(solution);
    toast({
      title: "Copied!",
      description: "Solution copied to clipboard",
    });
  };

  return (
    <div className="glass rounded-xl overflow-hidden animate-slide-up">
      <div className="p-4 border-b border-border/50 flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="p-2 rounded-lg bg-primary/10">
            <Sparkles className="w-5 h-5 text-primary" />
          </div>
          <h3 className="font-display text-lg">Solution</h3>
        </div>
        <Button
          variant="ghost"
          size="sm"
          onClick={copyToClipboard}
          className="gap-2"
        >
          <Copy className="w-4 h-4" />
          Copy
        </Button>
      </div>
      
      {capturedImage && (
        <div className="p-4 border-b border-border/50 bg-background/50">
          <p className="text-xs text-muted-foreground mb-2 font-display">Analyzed Image:</p>
          <img 
            src={capturedImage} 
            alt="Captured math problem" 
            className="max-h-40 object-contain rounded-lg"
          />
        </div>
      )}
      
      <div className="p-6 prose prose-invert prose-sm max-w-none">
        <ReactMarkdown
          components={{
            h1: ({ children }) => <h1 className="text-xl font-display text-foreground mt-4 mb-2">{children}</h1>,
            h2: ({ children }) => <h2 className="text-lg font-display text-foreground mt-4 mb-2">{children}</h2>,
            h3: ({ children }) => <h3 className="text-base font-display text-foreground mt-3 mb-2">{children}</h3>,
            p: ({ children }) => <p className="text-muted-foreground mb-3 leading-relaxed">{children}</p>,
            strong: ({ children }) => <strong className="text-primary font-semibold">{children}</strong>,
            code: ({ children }) => (
              <code className="bg-secondary px-2 py-1 rounded text-primary font-display text-sm">
                {children}
              </code>
            ),
            pre: ({ children }) => (
              <pre className="bg-secondary p-4 rounded-lg overflow-x-auto my-4">
                {children}
              </pre>
            ),
            ul: ({ children }) => <ul className="list-disc list-inside space-y-1 mb-3">{children}</ul>,
            ol: ({ children }) => <ol className="list-decimal list-inside space-y-1 mb-3">{children}</ol>,
            li: ({ children }) => <li className="text-muted-foreground">{children}</li>,
          }}
        >
          {solution}
        </ReactMarkdown>
      </div>
      
      <div className="p-4 border-t border-border/50 bg-primary/5 flex items-center gap-2">
        <CheckCircle className="w-4 h-4 text-primary" />
        <span className="text-sm text-muted-foreground">Solution generated by AI</span>
      </div>
    </div>
  );
};
